CREATE TABLE `evaluaciondesempeno` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombreTrabajador` varchar(255) DEFAULT NULL,
  `cargoDesempeno` varchar(255) DEFAULT NULL,
  `fechaContratacion` date DEFAULT NULL,
  `antiguedad` int(11) DEFAULT NULL,
  `correo` varchar(255) DEFAULT NULL,
  `funcionesA1` int(11) DEFAULT NULL,
  `funcionesA2` int(11) DEFAULT NULL,
  `funcionesA3` int(11) DEFAULT NULL,
  `funcionesA4` int(11) DEFAULT NULL,
  `conocimientosB1` int(11) DEFAULT NULL,
  `conocimientosB2` int(11) DEFAULT NULL,
  `conocimientosB3` int(11) DEFAULT NULL,
  `conocimientosB4` int(11) DEFAULT NULL,
  `supervisionC1` int(11) DEFAULT NULL,
  `supervisionC2` int(11) DEFAULT NULL,
  `supervisionC3` int(11) DEFAULT NULL,
  `supervisionC4` int(11) DEFAULT NULL,
  `desempenaD1` int(11) DEFAULT NULL,
  `desempenaD2` int(11) DEFAULT NULL,
  `desempenaD3` int(11) DEFAULT NULL,
  `desempenaD4` int(11) DEFAULT NULL,
  `reaccionaE1` int(11) DEFAULT NULL,
  `reaccionaE2` int(11) DEFAULT NULL,
  `reaccionaE3` int(11) DEFAULT NULL,
  `reaccionaE4` int(11) DEFAULT NULL,
  `consigueF1` int(11) DEFAULT NULL,
  `consigueF2` int(11) DEFAULT NULL,
  `consigueF3` int(11) DEFAULT NULL,
  `consigueF4` int(11) DEFAULT NULL,
  `manejarG1` int(11) DEFAULT NULL,
  `manejarG2` int(11) DEFAULT NULL,
  `manejarG3` int(11) DEFAULT NULL,
  `manejarG4` int(11) DEFAULT NULL,
  `estandaresH1` int(11) DEFAULT NULL,
  `estandaresH2` int(11) DEFAULT NULL,
  `estandaresH3` int(11) DEFAULT NULL,
  `estandaresH4` int(11) DEFAULT NULL,
  `equipoI1` int(11) DEFAULT NULL,
  `equipoI2` int(11) DEFAULT NULL,
  `equipoI3` int(11) DEFAULT NULL,
  `equipoI4` int(11) DEFAULT NULL,
  `ayudaJ1` int(11) DEFAULT NULL,
  `ayudaJ2` int(11) DEFAULT NULL,
  `ayudaJ3` int(11) DEFAULT NULL,
  `ayudaJ4` int(11) DEFAULT NULL,
  `personalK1` int(11) DEFAULT NULL,
  `personalK2` int(11) DEFAULT NULL,
  `personalK3` int(11) DEFAULT NULL,
  `personalK4` int(11) DEFAULT NULL,
  `reunionL1` int(11) DEFAULT NULL,
  `reunionL2` int(11) DEFAULT NULL,
  `reunionL3` int(11) DEFAULT NULL,
  `reunionL4` int(11) DEFAULT NULL,
  `ocasional` varchar(255) DEFAULT NULL,
  `mitad` varchar(255) DEFAULT NULL,
  `frecuente` varchar(255) DEFAULT NULL,
  `siempre` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `evaluaciondesempeno` (`id`, `estado`, `nombreTrabajador`, `cargoDesempeno`, `fechaContratacion`, `antiguedad`, `correo`, `funcionesA1`, `funcionesA2`, `funcionesA3`, `funcionesA4`, `conocimientosB1`, `conocimientosB2`, `conocimientosB3`, `conocimientosB4`, `supervisionC1`, `supervisionC2`, `supervisionC3`, `supervisionC4`, `desempenaD1`, `desempenaD2`, `desempenaD3`, `desempenaD4`, `reaccionaE1`, `reaccionaE2`, `reaccionaE3`, `reaccionaE4`, `consigueF1`, `consigueF2`, `consigueF3`, `consigueF4`, `manejarG1`, `manejarG2`, `manejarG3`, `manejarG4`, `estandaresH1`, `estandaresH2`, `estandaresH3`, `estandaresH4`, `equipoI1`, `equipoI2`, `equipoI3`, `equipoI4`, `ayudaJ1`, `ayudaJ2`, `ayudaJ3`, `ayudaJ4`, `personalK1`, `personalK2`, `personalK3`, `personalK4`, `reunionL1`, `reunionL2`, `reunionL3`, `reunionL4`, `ocasional`, `mitad`, `frecuente`, `siempre`) VALUES
(1, 1, 'Alejandra', 'Gerente', '2024-06-04', 10, 'mariadelcarmencallemontalvo@gmail.com', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '0.00', '0.00', '0.00', '0.00'),
(2, 1, 'Ruddy Gerardo', 'Administrador', '2024-06-04', 0, 'cjdnjc@gmail.com', 50, 0, 0, 0, 0, 60, 0, 0, 0, 65, 0, 0, 0, 60, 0, 0, 0, 60, 0, 0, 0, 0, 60, 0, 0, 0, 55, 0, 0, 0, 5, 0, 0, 0, 5, 0, 0, 0, 50, 0, 0, 0, 5, 0, 0, 0, 5, 0, '1.04', '10.21', '11.56', '0.00');

--
-- solo copiar y pegar a la base de datos no tiene relacion es una tabla independiente