
CREATE TABLE reclamos (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  correo VARCHAR(100) NOT NULL,
  telefono VARCHAR(100) NOT NULL,
  reclamo TEXT NOT NULL,
  estado BOOLEAN NOT NULL DEFAULT 1
);
